version: "3.8"
services:
  gateway-svc:
    build:
      dockerfile: Dockerfile
      args:
        - USERS_URL=$USERS_URL
        - TRAINERS_URL=$TRAINERS_URL
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - USERS_URL=$USERS_URL
      - TRAINERS_URL=$TRAINERS_URL
    ports:
      - "8080:8080"
