name: Docker Hub Upload Workflow

on:
  pull_request:
    branches:
      - main
    paths: 
      - cmd/**
      - internal/**
      - Dockerfile
      - docker-compose.yml
    types:
      - closed
  workflow_dispatch:

jobs:
  
  push-docker-image:
    runs-on: ubuntu-latest
        
    steps:
    
      - uses: actions/checkout@v3
    
      - name: Create firebase token file      
        run: |
          echo "${FIREBASE}" >> firebase.json
        shell: bash
        env:
          FIREBASE: ${{ secrets.FIREBASE }}
   
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push        
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fiufit-api-gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push-docker-image
    steps:      
      - name: checkout
        uses: actions/checkout@v3

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
     
      - name: Rollout deployment
        env:
          CREDENTIALS: ${{secrets.KUBE_CREDENTIALS}}
        run: |
          echo "$CREDENTIALS" >> okteto-kube.config
          export KUBECONFIG=$PWD/okteto-kube.config:${KUBECONFIG:-$HOME}/.kube/config}
          kubectl rollout restart deployment/service-external-gateway --namespace=franco-jyq
